/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcaraRouteImport } from './routes/acara'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnggotaRouteImport } from './routes/_authenticated/anggota'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnggotaRouteImport } from './routes/_authenticated/admin.anggota'
import { Route as AuthenticatedAdminPengaturanRouteImport } from './routes/_authenticated/admin.pengaturan'
import { Route as AuthenticatedAdminPersetujuanRouteImport } from './routes/_authenticated/admin.persetujuan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcaraRoute = AcaraRouteImport.update({
  id: '/acara',
  path: '/acara',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnggotaRoute = AuthenticatedAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnggotaRoute =
  AuthenticatedAdminAnggotaRouteImport.update({
    id: '/admin/anggota',
    path: '/admin/anggota',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPengaturanRoute =
  AuthenticatedAdminPengaturanRouteImport.update({
    id: '/admin/pengaturan',
    path: '/admin/pengaturan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPersetujuanRoute =
  AuthenticatedAdminPersetujuanRouteImport.update({
    id: '/admin/persetujuan',
    path: '/admin/persetujuan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acara': typeof AcaraRoute
  '/auth': typeof AuthRoute
  '/anggota': typeof AuthenticatedAnggotaRoute
  '/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/persetujuan': typeof AuthenticatedAdminPersetujuanRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acara': typeof AcaraRoute
  '/auth': typeof AuthRoute
  '/anggota': typeof AuthenticatedAnggotaRoute
  '/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/persetujuan': typeof AuthenticatedAdminPersetujuanRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acara': typeof AcaraRoute
  '/auth': typeof AuthRoute
  '/_authenticated/anggota': typeof AuthenticatedAnggotaRoute
  '/_authenticated/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/_authenticated/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/_authenticated/admin/persetujuan': typeof AuthenticatedAdminPersetujuanRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acara'
    | '/auth'
    | '/anggota'
    | '/admin/anggota'
    | '/admin/pengaturan'
    | '/admin/persetujuan'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acara'
    | '/auth'
    | '/anggota'
    | '/admin/anggota'
    | '/admin/pengaturan'
    | '/admin/persetujuan'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acara'
    | '/auth'
    | '/_authenticated/anggota'
    | '/_authenticated/admin/anggota'
    | '/_authenticated/admin/pengaturan'
    | '/_authenticated/admin/persetujuan'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcaraRoute: typeof AcaraRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acara': {
      id: '/acara'
      path: '/acara'
      fullPath: '/acara'
      preLoaderRoute: typeof AcaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/anggota': {
      id: '/_authenticated/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AuthenticatedAnggotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/anggota': {
      id: '/_authenticated/admin/anggota'
      path: '/admin/anggota'
      fullPath: '/admin/anggota'
      preLoaderRoute: typeof AuthenticatedAdminAnggotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pengaturan': {
      id: '/_authenticated/admin/pengaturan'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AuthenticatedAdminPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/persetujuan': {
      id: '/_authenticated/admin/persetujuan'
      path: '/admin/persetujuan'
      fullPath: '/admin/persetujuan'
      preLoaderRoute: typeof AuthenticatedAdminPersetujuanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnggotaRoute: typeof AuthenticatedAnggotaRoute
  AuthenticatedAdminAnggotaRoute: typeof AuthenticatedAdminAnggotaRoute
  AuthenticatedAdminPengaturanRoute: typeof AuthenticatedAdminPengaturanRoute
  AuthenticatedAdminPersetujuanRoute: typeof AuthenticatedAdminPersetujuanRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnggotaRoute: AuthenticatedAnggotaRoute,
  AuthenticatedAdminAnggotaRoute: AuthenticatedAdminAnggotaRoute,
  AuthenticatedAdminPengaturanRoute: AuthenticatedAdminPengaturanRoute,
  AuthenticatedAdminPersetujuanRoute: AuthenticatedAdminPersetujuanRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcaraRoute: AcaraRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
